ALTER TABLE "jobs"
  ADD COLUMN IF NOT EXISTS "responsibilities" TEXT[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS "country" TEXT DEFAULT 'RW',
  ADD COLUMN IF NOT EXISTS "category" TEXT,
  ADD COLUMN IF NOT EXISTS "workplace_type" TEXT NOT NULL DEFAULT 'ON_SITE',
  ADD COLUMN IF NOT EXISTS "salary_text" TEXT,
  ADD COLUMN IF NOT EXISTS "external_apply_enabled" BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS "external_apply_url" TEXT;
