#!/bin/sh
set -e

# Defaults match Coolify durable network aliases / Compose DNS names.
IDENTITY_SERVICE_HOST=${IDENTITY_SERVICE_HOST:-identity-service}
IDENTITY_SERVICE_PORT=${IDENTITY_SERVICE_PORT:-3011}
PLATFORM_SERVICE_HOST=${PLATFORM_SERVICE_HOST:-platform-service}
PLATFORM_SERVICE_PORT=${PLATFORM_SERVICE_PORT:-3012}
RECRUITMENT_SERVICE_HOST=${RECRUITMENT_SERVICE_HOST:-recruitment-service}
RECRUITMENT_SERVICE_PORT=${RECRUITMENT_SERVICE_PORT:-3013}
TALENT_POOL_SERVICE_HOST=${TALENT_POOL_SERVICE_HOST:-talent-pool-service}
TALENT_POOL_SERVICE_PORT=${TALENT_POOL_SERVICE_PORT:-3014}
NOTIFICATION_SERVICE_HOST=${NOTIFICATION_SERVICE_HOST:-notification-service}
NOTIFICATION_SERVICE_PORT=${NOTIFICATION_SERVICE_PORT:-3015}
PAYROLL_SERVICE_HOST=${PAYROLL_SERVICE_HOST:-payroll-service}
PAYROLL_SERVICE_PORT=${PAYROLL_SERVICE_PORT:-3016}
DOCUMENT_SERVICE_HOST=${DOCUMENT_SERVICE_HOST:-document-service}
DOCUMENT_SERVICE_PORT=${DOCUMENT_SERVICE_PORT:-3018}
LENDING_SERVICE_HOST=${LENDING_SERVICE_HOST:-lending-service}
LENDING_SERVICE_PORT=${LENDING_SERVICE_PORT:-3021}

export IDENTITY_SERVICE_HOST IDENTITY_SERVICE_PORT \
  PLATFORM_SERVICE_HOST PLATFORM_SERVICE_PORT \
  RECRUITMENT_SERVICE_HOST RECRUITMENT_SERVICE_PORT \
  TALENT_POOL_SERVICE_HOST TALENT_POOL_SERVICE_PORT \
  NOTIFICATION_SERVICE_HOST NOTIFICATION_SERVICE_PORT \
  PAYROLL_SERVICE_HOST PAYROLL_SERVICE_PORT \
  DOCUMENT_SERVICE_HOST DOCUMENT_SERVICE_PORT \
  LENDING_SERVICE_HOST LENDING_SERVICE_PORT

echo "E-Watu gateway upstreams:"
echo "  identity:     ${IDENTITY_SERVICE_HOST}:${IDENTITY_SERVICE_PORT}"
echo "  platform:     ${PLATFORM_SERVICE_HOST}:${PLATFORM_SERVICE_PORT}"
echo "  recruitment:  ${RECRUITMENT_SERVICE_HOST}:${RECRUITMENT_SERVICE_PORT}"
echo "  talent-pool:  ${TALENT_POOL_SERVICE_HOST}:${TALENT_POOL_SERVICE_PORT}"
echo "  notification: ${NOTIFICATION_SERVICE_HOST}:${NOTIFICATION_SERVICE_PORT}"
echo "  payroll:      ${PAYROLL_SERVICE_HOST}:${PAYROLL_SERVICE_PORT}"
echo "  document:     ${DOCUMENT_SERVICE_HOST}:${DOCUMENT_SERVICE_PORT}"
echo "  lending:      ${LENDING_SERVICE_HOST}:${LENDING_SERVICE_PORT}"

# Only substitute listed vars — preserve nginx $upstream, $host, etc.
envsubst '${IDENTITY_SERVICE_HOST} ${IDENTITY_SERVICE_PORT} ${PLATFORM_SERVICE_HOST} ${PLATFORM_SERVICE_PORT} ${RECRUITMENT_SERVICE_HOST} ${RECRUITMENT_SERVICE_PORT} ${TALENT_POOL_SERVICE_HOST} ${TALENT_POOL_SERVICE_PORT} ${NOTIFICATION_SERVICE_HOST} ${NOTIFICATION_SERVICE_PORT} ${PAYROLL_SERVICE_HOST} ${PAYROLL_SERVICE_PORT} ${DOCUMENT_SERVICE_HOST} ${DOCUMENT_SERVICE_PORT} ${LENDING_SERVICE_HOST} ${LENDING_SERVICE_PORT}' \
  < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf

exec "$@"
